pathappend %PREFIX/bin           		PATH
pathappend %PREFIX/include	 		C_INCLUDE_PATH
pathappend %PREFIX/include 			CPLUS_INCLUDE_PATH
pathappend %PREFIX/lib     			LIBRARY_PATH
pathappend %PREFIX/lib/python3.6/site-packages 	PYTHONPATH
pathappend %PREFIX/lib/python2.7/site-packages  PYTHONPATH
pathappend %PREFIX/share/man			MANPATH
pathappend %PREFIX/share/aclocal		ACLOCAL_PATH
pathappend %PREFIX/lib/pkgconfig		PKG_CONFIG_PATH
pathappend %PREFIX/share/pkgconfig		PKG_CONFIG_PATH
pathappend %PREFIX				CMAKE_PREFIX_PATH
