#!/usr/pkgs/bash/bin/bash
########################################################################
# Begin iptables
#
# Description : Start iptables
#
# Authors     : Ken Moffat - ken@linuxfromscratch.org
#               Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:          iptables
# Required-Start:    
# Should-Start:
# Required-Stop:     $local_fs
# Should-Stop:
# Default-Start:     3 4 5
# Default-Stop:     
# Short-Description: Loads iptables rules.
# Description:       Iptables provides firewall for Linux systems.
# X-LFS-Provided-By: BLFS / LFS 7.0
### END INIT INFO

. /usr/etc/rc.d/init.d/init-functions

#$LastChangedBy: krejzi $
#$Date: 2013-06-11 11:01:46 -0500 (Tue, 11 Jun 2013) $

case "$1" in
    start)
        if [ -x /usr/etc/rc.d/rc.iptables ]; then
          log_info_msg "Starting iptables..."
          /usr/etc/rc.d/rc.iptables
          evaluate_retval
        fi
        ;;

    lock)
        log_info_msg "Locking system iptables firewall..."
        /usr/pkgs/iptables/bin/iptables --policy INPUT   DROP
        /usr/pkgs/iptables/bin/iptables --policy OUTPUT  DROP
        /usr/pkgs/iptables/bin/iptables --policy FORWARD DROP
        /usr/pkgs/iptables/bin/iptables           --flush
        /usr/pkgs/iptables/bin/iptables -t nat    --flush
        /usr/pkgs/iptables/bin/iptables -t mangle --flush
        /usr/pkgs/iptables/bin/iptables           --delete-chain
        /usr/pkgs/iptables/bin/iptables -t nat    --delete-chain
        /usr/pkgs/iptables/bin/iptables -t mangle --delete-chain
        /usr/pkgs/iptables/bin/iptables -A INPUT  -i lo -j ACCEPT
        /usr/pkgs/iptables/bin/iptables -A OUTPUT -o lo -j ACCEPT
        evaluate_retval
        ;;

    clear)
        log_info_msg "Clearing system iptables iptables..."
        /usr/pkgs/iptables/bin/iptables --policy INPUT   ACCEPT
        /usr/pkgs/iptables/bin/iptables --policy OUTPUT  ACCEPT
        /usr/pkgs/iptables/bin/iptables --policy FORWARD ACCEPT
        /usr/pkgs/iptables/bin/iptables           --flush
        /usr/pkgs/iptables/bin/iptables -t nat    --flush
        /usr/pkgs/iptables/bin/iptables -t mangle --flush
        /usr/pkgs/iptables/bin/iptables           --delete-chain
        /usr/pkgs/iptables/bin/iptables -t nat    --delete-chain
        /usr/pkgs/iptables/bin/iptables -t mangle --delete-chain
        evaluate_retval
        ;;

    status)
        /usr/pkgs/iptables/bin/iptables           --numeric --list
        /usr/pkgs/iptables/bin/iptables -t nat    --numeric --list
        /usr/pkgs/iptables/bin/iptables -t mangle --numeric --list
        ;;

    *)
        echo "Usage: $0 {start|clear|lock|status}"
        exit 1
        ;;
esac

# End /etc/init.d/iptables

